/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacaster;

import java.awt.Graphics;
import java.awt.event.KeyEvent;

/**
 *
 * @author kouta
 */
public class CasterViewer extends javax.swing.JPanel {

    /**
     * Creates new form CasterViewer
     */
    public CasterViewer(Caster caster) {
        this.raycaster = caster;
        initComponents();
    }

    public CasterViewer() {
        this.raycaster = new Caster(Map.emptyMap(10));
        initComponents();
    }

    private Caster raycaster;

    public Caster getRaycaster() {
        return raycaster;
    }

    public void setRaycaster(Caster raycaster) {
        this.raycaster = raycaster;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        handleKeyEvent(evt);
    }//GEN-LAST:event_formKeyPressed

    public void handleKeyEvent(KeyEvent evt) {
        switch (evt.getKeyChar()) {
            case 'a':
            case 'A':
                raycaster.turnLeft();
                break;
            case 'd':
            case 'D':
                raycaster.turnRight();
                break;
            case 'w':
            case 'W':
                raycaster.forward();
                break;
            case 's':
            case 'S':
                raycaster.backward();
                break;
        }
        this.repaint();
    }

    @Override
    public void paint(Graphics grphcs) {
        grphcs.clearRect(0, 0, getWidth(), getHeight());
        grphcs.drawImage(raycaster.render(), 0, 0, getWidth(), getHeight(), null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
