/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacaster;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author kouta
 */
public class MapEditorInternalFrame extends javax.swing.JInternalFrame {

    private Minimap minimap;

    /**
     * Creates new form MapEditor
     */
    public MapEditorInternalFrame(Minimap minimap) {
        this.minimap = minimap;
        initComponents();
    }

    @Override
    public void paint(Graphics grphcs) {
        grphcs.setColor(Color.WHITE);
        grphcs.clearRect(0, 0, getWidth(), getHeight());
        grphcs.drawImage(minimap.renderMinimap(false), getWidth(), getHeight(), null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Map map = minimap.getRaycaster().getMap();
        int xcoord = (int) (((double)evt.getX() / (double)getWidth()) * map.getWidth());
        int ycoord = (int) (((double)evt.getY() / (double)getHeight()) * map.getHeight());
        
        map.set(ycoord, xcoord, (byte)(map.atPoint(ycoord, xcoord)^1));
        repaint();
    }//GEN-LAST:event_formMouseClicked

    void setMinimap(Minimap minimap) {
        this.minimap = minimap;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
